language: cpp

compiler:
  - clang
  - gcc

before_install:
  - git submodule update --init --recursive

install:
  - if [ "$CC" = "gcc" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CC" = "clang" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

before_script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_TESTS=YES

script:
  - make
  - ./spec/spec_runner

os:
  - linux

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - cmake-data
      - cmake
      - gcc-5
      - g++-5
      - clang-3.7
