os: Visual Studio 2015

platform: x86

install:
  - git submodule update --init --recursive

build_script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_TESTS=YES
  - cmake --build .

test_script:
  - ps: c:\projects\cppspec\build\spec\Debug\spec_runner.exe
