name: Build and Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        compiler: [native, llvm]
        os: [ubuntu-latest, windows-latest]
        exclude:
          - os: windows-latest
            compiler: llvm

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Use LLVM and Clang
      run: |
        echo "CC=clang-18" >> $GITHUB_ENV
        echo "CXX=clang++-18" >> $GITHUB_ENV
      if: ${{ matrix.compiler != 'native' }}

    - name: Configure
      run: cmake -B build -DCPPSPEC_BUILD_TESTS=YES

    - name: Build
      run: cmake --build build --config Release

    - name: Test
      run: ctest --test-dir build --build-config Release --output-on-failure

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Test Results (${{ matrix.os }} - ${{ matrix.compiler }})
        path: build/spec/results/*.xml

  publish-test-results:
    name: "Publish Tests Results"
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      checks: write

      # only needed unless run with comment_mode: off
      pull-requests: write

    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "artifacts/**/*.xml"