name: Build and Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        compiler: [native, llvm]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "15"
        env: ${{ matrix.compiler == 'llvm' }}
      if: ${{ matrix.compiler == 'llvm' }}

    - name: Configure  
      run: cmake -Bbuild -DBUILD_TESTS=YES

    - name: Build
      run: cmake --build build --config Release

    - name: Test
      run: ctest --test-dir build